### ISSUE TITLE
Breaking word across elements

### ISSUE THREAD

**Issue by dickieirwin** [ismarslomic/angular-read-more#10]
![screen shot 2016-02-23 at 3 29 53 pm](https://cloud.githubusercontent.com/assets/5124035/13240014/a10da970-da43-11e5-8279-f8c131276ab4.png)
![screen shot 2016-02-23 at 3 29 49 pm](https://cloud.githubusercontent.com/assets/5124035/13240015/a10fc02a-da43-11e5-8165-05b1c22c32c2.png)

If the character limit ends in the middle of a word that word is split over the two <p> elements when the more-text is shown. 

Expected behaviour would be the more-text <p> element would contain the whole text and the read more would toggle ng-show between both elements?

**Comment by ismarslomic** [comment]
Thanks @dickieirwin! I agree that this feature would be useful. Would you be able to create a pull request for this, and I ll make sure to merge it?

**Comment by dickieirwin** [comment]
Sorry they ended up as two pull requests and I only applied the changes to the /src files... but you can see what needs doing should be a 5 min job

**Comment by dickieirwin** [comment]
Great directive by the way!
