### ISSUE TITLE
Avoid <pre> tags in the template

### ISSUE THREAD

**Issue by mdantonio** [ismarslomic/angular-read-more#11]
I tried to integrate the angular-read-more library into a web app and everything works fine except for the _pre_ tags in the template (used to wrap both short and long texts). 
_pre_ is a pretty invasive html tag and it strongly modifies the page layout. To make a simple test i manually substituted _pre_ tags with _span_ tags and the library seem still to work for me (with no impact on the page layout).
May be possible to optionally use _span_ instead of _pre_ to wrap text?
Many thanks

**Comment by th00ber** [comment]
+1
Seems to be new no ? Directive works great for me for long time but recently I have some visual issue with the <pre>

**Comment by th00ber** [comment]
https://github.com/ismarslomic/angular-read-more/commit/d81522dbdddac699cd0d95f451c643101ea6413f#diff-1fbb7efb9e973f0c41e05b097f01b00e

It's due tu this commit.
And if the text is long the horizontal scrollbar is displayed instead of going to a new line.

**Comment by ismarslomic** [comment]
Thanks @th00ber  and @mdantonio. Reason why we switched to pre in stead of span was in order to preserve line breaks in the text. However, this is now solved in 5373ed9 where I have used style in stead and switched back to span

**Comment by mdantonio** [comment]
Many thanks!
