### ISSUE TITLE
Why an '@' binding for text?

### ISSUE THREAD

**Issue by arg20** [ismarslomic/angular-read-more#12]
The purpose of this directive is to summarise a long piece of text, why then force the user to use {{ }} inside the `hm-text` attribute? Not only does the DOM end up with a huge attribute, but if the user will always have to use bindings like that, the extra `{{ }}` look ugly. I suggest moving from a `'@'` binding to `'='`. What do you think?

**Comment by ismarslomic** [comment]
@arg20: I see your point, but switching to '=' makes also two-ways binding for this attribute. However, Im fine with moving over to '='. Would you be able to make a pull request for this change?

**Comment by ismarslomic** [comment]
@arg20: DOM will look identical if you use '@' or '=' as far as I can see.

**Comment by ismarslomic** [comment]
Closing the issue because of inactivity. Reopen if still applicable
