### ISSUE TITLE
Read more adds a single space that breaks the text 

### ISSUE THREAD

**Issue by Yabood** [ismarslomic/angular-read-more#20]
If the limit falls on a non-empty space, cutting off a word in the middle, the 'show more' will add a single space to the word after its clicked. In the demo you have [here](http://codepen.io/ismarslomic/pen/yYMvrz) change the limit to 198 instead of 200. The '...' will appear on the last two letters of the word "mauris". Once you click show more, the word will be displayed like this "mauri  s".

**Comment by parveensaini5** [comment]
Edit directive and delete \n between 
<span ng-bind-html=\"vm.lessText\" style=\"white-space:pre-wrap;\"></span>

**\n**

<span ng-show=\"vm.showMoreText\" class=\"more-show-hide\" ng-bind-html=\"vm.moreText\" style=\"white-space:pre-wrap;\"></span>

**Comment by ismarslomic** [comment]
Can you please make an pull request?

**Comment by bgsavage** [comment]
Any updates on this?  I'm seeing the same issue...

**Comment by bgsavage** [comment]
Hi - I've made a pull request for a fix to this issue.

**Comment by ismarslomic** [comment]
Solved in 4660d51725099dbc6bca7b5103f5128fa9ae9c5d
