### ISSUE TITLE
Disable debug

### ISSUE THREAD

**Issue by williamoliveira** [ismarslomic/angular-read-more#24]
There needs to be a way to disable the package's debug messages, its flooding my console.
Also [this](https://github.com/ismarslomic/angular-read-more/blob/master/src/readmore.js#L7) is not cool, as its app wide

**Comment by ruisilva450** [comment]
^This. And I'm getting the following error related to this.
`angular.js:63 Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module hm.readmore due to:
TypeError: e.debugEnabled is not a function`

**Comment by rodneyjoyce** [comment]
Agree, this makes it very hard to debug other things

**Comment by lfbn** [comment]
With the debug enabled at false it shouldn't show anything in the console.

**Comment by ismarslomic** [comment]
Fixed in a56d8f35dd0291eb70257d104583f7e968c384b2
