### ISSUE TITLE
Not working on first time

### ISSUE THREAD

**Issue by patelhir** [ismarslomic/angular-read-more#29]
It is not working on initialization. It is working fine if i change some value in "text" textarea. Can you help me out how to sore out this?

**Comment by lfbn** [comment]
Is working with me. Maybe is loading? Some error appears in the console? Which browser are you using?

**Comment by patelhir** [comment]
I have taken someone's help and he edited line#132 with this one and it started working. 

if (!angular.isDefined(vm.lessText) || newValue != oldValue)

**Comment by lfbn** [comment]
Strange. Can't replicate the problem. How is you calling the directive?

**Comment by itg33k** [comment]
I have exactly the same problem. I am loading my data using an API and $resource. When the data is returned nothing is shown for the directive. If I comment out line 132 it works.

**Comment by simonered** [comment]
It depends on what version of Angular you are using.
Starting from Angular 1.5 this deprecation warning appears in official documentation:

> Deprecation warning: although bindings for non-ES6 class controllers are currently bound to this before the controller constructor is called, this use is now deprecated. Please place initialization code that relies upon bindings inside a $onInit method on the controller, instead.

You need to call `initialize()` into a new `$onInit` function in `hmReadMoreController`(line 127): replace `initialize();` with `vm.$onInit = initialize;`

I've created a PR.

**Comment by clausiobarbosa** [comment]
thks @simonered this resolved the issue.

**Comment by ismarslomic** [comment]
Solved in a69c7bb4161e42f5bd4c481fc2e47c7e7e12f79d by upgrading to Angular v1.6.4
