### ISSUE TITLE
Register as Bower package

### ISSUE THREAD

**Issue by ismarslomic** [ismarslomic/angular-read-more#3]
I found this angular directive very useful. Would it be possible to publish it at npmjs.com? Let me know if you need any help on doing this.

See also: https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by ismarslomic** [comment]
Sorry, I ment registert as Bower packag: http://bower.io/docs/creating-packages/#register

**Comment by hiteshmodha** [comment]
@ismarslomic thanks for using this directive, I will surely register npm.js and bower package.

**Comment by ismarslomic** [comment]
I have done some modifications to your code. I can do a pull request to merge in the code if you would like?

**Comment by hiteshmodha** [comment]
Thanks @ismarslomic . Pull request are always welcome.

**Comment by ismarslomic** [comment]
@hiteshmodha see Pull request https://github.com/hiteshmodha/angular-read-more/pull/4

**Comment by ismarslomic** [comment]
Done
