### ISSUE TITLE
<pre>

### ISSUE THREAD

**Issue by limulidae** [ismarslomic/angular-read-more#5]
is this tested with <pre>?
With <pre>, it comes with a large textbox+scrollbar, which is not what I want.

**Comment by ismarslomic** [comment]
@limulidae, could you please recreate the issue with one codepen example? You can take basis in existing demo here http://codepen.io/ismarslomic/pen/yYMvrz

**Comment by ismarslomic** [comment]
@limulidae, could you please recreate the issue with one codepen example? You can take basis in existing demo here http://codepen.io/ismarslomic/pen/yYMvrz

**Comment by ismarslomic** [comment]
@limulidae, please provide more information on how to recreate the issues you are facing or add a Codepen example. Otherwise this issue will be closed soon.

**Comment by limulidae** [comment]
sorry for my late response,

I just use your code pen, and replace < p > with < pre >

**Comment by ismarslomic** [comment]
@limulidae Im still not sure where you are in the code. Can you please look at the latest version of the code and be specific on which file and codeline you are refering to? I can´t see that < p > is used neither in the source code nor in the CodePen example.

**Comment by limulidae** [comment]
in your code pen http://codepen.io/ismarslomic/pen/yYMvrz

replace < div > with  < pre >

< pre 
    hm-read-more 
    hm-text="{{text}}" 
    hm-limit="{{limit}}" 
    hm-more-text="{{moreText}}" 
    hm-less-text="{{lessText}}" 
    hm-dots-class="{{dotsClass}}" 
    hm-link-class="{{linkClass}}"
< / pre >

**Comment by ismarslomic** [comment]
@limulidae can you please verify if the latest version (1.0.4) of angular-read-more is solving this issue?

**Comment by limulidae** [comment]
fixed
