### ISSUE TITLE
Doesn't preserve line breaks

### ISSUE THREAD

**Issue by Draffodx** [ismarslomic/angular-read-more#8]
In my application a user enters text into a textarea, when they enter a line break the value \n gets added to the text, This gets stored and is pulled back for display with the read-more plugin but the plugin just ignores the line break \n value. Is there an option to tell it to respect the line breaks?

Codepen - http://codepen.io/anon/pen/adXNXJ

When I try to force it via CSS it leaves a large space between the cut off value of the text and the read more/read less text

Codepen for that - http://codepen.io/anon/pen/dGaMLd

**Comment by ismarslomic** [comment]
\n is not preserved so solution is to switch from span to pre element or set preserve-line in css, as you did.

Need to look at this. If you can do pull request that would be great

**Comment by Draffodx** [comment]
Add pull request - https://github.com/ismarslomic/angular-read-more/pull/9

**Comment by ismarslomic** [comment]
Thanks!
